### ISSUE TITLE
Unable to run my protractor tests

### ISSUE THREAD

**Issue by kuhu19** [jenkinsci/selenium-plugin#105]
My protractor tests run fine when using a local selenium server or even a local grid which I created but I am not able to connect to selenium-plugin created grid in jenkins. This is the error I am getting:

`[20:09:56] I/hosted - Using the selenium server at http://localhost:4000/wd/hub
[20:09:57] E/launcher - Error forwarding the new session Empty pool of VM for se
tup Capabilities [{count=1, browserName=chrome, chromeOptions={args=[disable-inf
obars=true], prefs={download={default_directory=D:\soft\myrepo\ProtractorDemo\ca
lculator\fileDownload}, credentials_enable_service=false}}, version=ANY, platfor
m=ANY}]`

The plugin home looks like this:

`Host: localhost

Port: 4000

Status

Online

Running at localhost:4000.

See Console Output and Grid Web Console for detailed status and configuration

Selenium 1 clients should connect as follow:

Selenium selenium = new DefaultSelenium("localhost", 4000, "*firefox", "http://my.test.site.org/");
Selenium 2 clients should connect as follow:

WebDriver driver = new RemoteWebDriver(new URL("http://localhost:4000/wd/hub"), capability);`

**Comment by Mobrockers** [comment]
Are any nodes connected to your hub? It looks like no nodes could be started.

**Comment by kuhu19** [comment]
The behavior is inconsistent. Sometimes they are coming as connected, sometimes not.

**Comment by kuhu19** [comment]
I think what is happening here is that I have marked one node is offline. Now the plugin is connected to that node but cannot run tests there as it is offline. So, whenever tests are connected to that node, they fail. Do you think this is possible?

**Comment by Mobrockers** [comment]
The plugin does not decide where a test is executed, this is all done by selenium hub and I doubt there are any issues there. The only thing the plugin does is decide where a node is started based on your setup, and how the node is going to be setup. I am pretty sure the issue is somewhere in your setup and not necessarily in the plugin.

**Comment by kuhu19** [comment]
I agree that it is highly unlikely selenium hub is not working correctly
here. I was saying that maybe plugin started a node for a node marked
offline but as the node was offline, tests routed to this node failed.

**Comment by Mobrockers** [comment]
As I said, test routing is done by selenium hub, the plugin has no control
over this. The plugin simply tries to start nodes according to your setup.
If a node cannot be created for any reason such as a slave being
unavailable, or if a node cannot be reached, then it simply will not get
routed to it because the hub will not know about the node. The only thing
the plugin does is start nodes. Everything else is selenium hub.

**Comment by kuhu19** [comment]
Ok, thank you for your insights on how the plugin works. Touch can close
this issue now. Thanks for all your help!
