### ISSUE TITLE
v2.2 Configuration Creation: Web Driver Node : Can't add Opera Browser

### ISSUE THREAD

**Issue by JaysonRaymond** [jenkinsci/selenium-plugin#17]
Nothing occurs when attempting to add an Opera Browser configuration.

**Comment by Mobrockers** [comment]
Closing because of outdated version. Please open a new issue if this is still present in new version.

**Comment by JaysonRaymond** [comment]
What?!! Glad I filed a bug that you closed without even testing... why did I bother? I'm done contributing here... (I'd test it,but I don't have access any longer).

**Comment by Mobrockers** [comment]
I closed the issue because this issue was fixed in version 2.4, and you yourself reported using version 2.2. It is also an issue from 2012. . As far as I know (and yes I did test) configuration creation works fine now, but since you gave little to no information about your problem, I added that if your issue still persists, you can open a new issue, since your issue obviously would then not be the issue I think you're referring to. 

If you were able to test and noticed your issue was still present, I would of course take a closer look, but from what I can gather from the information you provided this issue was fixed like two years ago. 

Do you really expect me to spend more effort than this on a one liner issue from four years ago that as far as I can tell hasn't been an issue in two years?

**Comment by JaysonRaymond** [comment]
Thanks for clarifying Rouke - if/when I get an opportunity to retest - I'll post results here.

Jayson
