### ISSUE TITLE
Provide option to not have selenium try to bind to external hostname

### ISSUE THREAD

**Issue by Mobrockers** [jenkinsci/selenium-plugin#60]
To fix issue #49 as described by @CRuppert

**Comment by Mobrockers** [comment]
I do not fully understand the issue here so if anyone could explain it to me some more? Why do we need to bind to all interfaces?

**Comment by CRuppert** [comment]
Sorry, its been over a year since I logged this issue, so I had to refresh myself.

Strictly speaking it doesn't HAVE to bind to all interfaces. From the behavior I noticed, it would try to bind to an interface based on a dns lookup for the jenkins server. This is not a desired behavior when behind a NAT router or Load balancer, or whatever, as the IP will never match a local network interface. An alternate solution would be to enumerate the network interfaces and allow the user to select which to bind to. The simplest solution would be to simply to bind to all local network interfaces.

Solving by creating a local hosts file entry for a local interface with the jenkins DNS name.. is undesirable at best.

**Comment by Mobrockers** [comment]
I don't think we are doing that though, and if we are then that is something selenium is doing, not us. We simply start the selenium-grid server with the arg -host hostname, which is either the Jenkins URL filled in the Jenkins URL config, or a custom hostname you can choose in the plugin config section of the Jenkins master config.

**Comment by CRuppert** [comment]
Right, but if that dns name configured for jenkins is routed to a public IP address of an ELB or Gateway, not one the machine, it cannot find that interface to bind to. As far as the config section, I think it's probably safe enough to say it's not documented well enough (as there are a few people chiming in on this issue) for it to be simple to use or setup.

Would it be better then, to use the machine name when supplying that argument, as it will always resolve to a network interface on that machine, rather than scraping configuration settings for a hostname?

**Comment by Mobrockers** [comment]
But then nodes from outside your network would be unable to ever connect to your grid, as they cannot find the hub my machine name, right?

I also do not get the issue with the public ip address. Why would selenium be unable to bind to that hostname?

**Comment by CRuppert** [comment]
Nodes outside the network can't connect ever anyway. The problem is that selenium host won't start if it can't find an interface to bind to.

Selenium can't bind to an IP address that doesn't belong to that machine. A public dns name for jenkins often won't be the hostname of the machine hosting it. A public DNS name will often be a record for for an IP address of an edge router or ELB device, NOT the hosting machine.

**Comment by Mobrockers** [comment]
Why wouldn't nodes outside the network be able to connect, as long as you set everything up to allow it?

And then it is the job of the edge router or load balancer to proxy the request back to the selenium hub, no? Would that not work fine? I suppose an option could be available in the settings to bind to all interfaces, but I do not think this should be the only option like pr #48 did.

In any case you can fill in whatever you want in the custom hostname option field. I haven't tested it but I wouldn't be surprised if you could set a machine name in there as well.

**Comment by CRuppert** [comment]
LOL. Absolutely nodes could if you set up your network correctly. You are correct.

Providing the option to bind to all interfaces, rather then hunting a network interface via IP address via dns lookup of configured jenkins url would completely solve the problem. :)

**Comment by Mobrockers** [comment]
@CRuppert Do you by any chance still have access to a selenium grid ran by this plugin? If so could you test the changes I made for this feature? If you can test it for me, load this file in your jenkins instance: https://dl.dropboxusercontent.com/u/5483751/selenium.hpi and set Selenium hostname resolver in Jenkins global configuration to no hostname resolver.

**Comment by Mobrockers** [comment]
I don't know if you still have access to a selenium grid running using this plugin, but I was wondering if you could test this updated plugin that contains a potential fix for this issue: https://dl.dropboxusercontent.com/u/5483751/selenium.hpi

Basically I added a new hostname resolver that always sets the hostname to "0.0.0.0" to listen on all interfaces. I don't really understand why you couldn't just set that as a custom hostname to begin with though.

**Comment by burdandrei** [comment]
hey @Mobrockers @CRuppert is right, the problem with resolving is exists, we in the end just ran standalone selenium hub. but i think this was one of a bug avoiding other from using your great plugin.
Cheers =)

**Comment by Mobrockers** [comment]
@burdandrei Do you recon setting the hostname to "0.0.0.0" is enough to fix this issue? Is there a reason this could not be done using the "static hostname" option?

**Comment by burdandrei** [comment]
@Mobrockers let me check it tomorrow and return to you.

**Comment by Mobrockers** [comment]
I doubt my change would fix the issue actually. You would want to still set the hostname because otherwise nodes won't know where to connect to, but this hostname is not the hostname the hub should listen on. Is that correct?

**Comment by Mobrockers** [comment]
How is this functionally different from just setting your own hostname in selenium config though. I still don't get the issue..

**Comment by Mobrockers** [comment]
I no longer believe this is actually needed, as I am not convinced this is not covered by the static hostname option. I will however leave this open in case anyone wants to enlighten me as to why the static hostname option does not suffice.

**Comment by Mobrockers** [comment]
No response, closing
