### ISSUE TITLE
Selenium node doesn't start on clicking the Start button.

### ISSUE THREAD

**Issue by sudheerpujar** [jenkinsci/selenium-plugin#97]
Hi 
I have created a Jenkins slave node with Launch Method  _Launch slave agents via Java Webstart method_. 
Note : The slave agent up and running.

I have attached [_Matching Type : Match nodes from a label expression (Expression = 'automation' )_] the selenium node with this agent via label mechanism. 

When I go to   **Selenium Node Management** page and click Start button  under **Matching configurations** nothing happens. 

However when I attached [as mention above] the selenium node, via labels, with any  other slave agents that use the Launch Method _Launch slave via excecution of command on the Master_ 

Anything I specific I need to do ?

**Comment by zdmeyers** [comment]
That depends on the OS and how you are running the JWS application. If your slaves are windows machines, and you are running the JWS app as a service, then you won't see anything on the screen even if your test cases appear to be executing. This is due to session 0 isolation that is a security feature built into Windows and is pretty much impossible to bypass. Running the slave-agent.jnlp file from the desktop by double-clicking it will allow you to see the browser opening and test cases executing. There are also registry hacks and other changes that need to be made to Windows depending on the version (and IE if you are using it) before a slave will run correctly with Selenium. You can google for these changes as they are well documented. Now, if the OS of your slaves is Linux, just use the connect over ssh mode and it should work OOTB.

**Comment by sudheerpujar** [comment]
Thanks for your kind help. 
Issue is resolved now, I am closing this issue
